FollowIt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('users.urls')),
    url(r'^shows/', include('shows.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

shows/urls.py
from django.conf.urls import url

from . import views

app_name = 'shows'
urlpatterns = [
    url(r'^(?P<show_id>[0-9]+)$', views.ShowView.as_view(), name="show"),
    url(r'^follow/', views.follow_shows, name='follow_show')
]

users/urls.py
from django.conf.urls import url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from . import views


app_name = 'users'
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^register/$', views.signup, name='register'),
    url(r'^followed/$', views.followed_shows, name='followed'),
    url(r'^followed/(?P<air_day>[a-zA-Z]+)/$', views.followed_shows, name='followed_day'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

users/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.


class Person(User):
    class Meta:
        proxy = True

    def is_following(self, show_id):
        """Return FollowedShows object if show_id matches else None"""
        try:
            return self.followedshows_set.get(show_id=show_id)
        except FollowedShows.DoesNotExist:
            return None


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class FollowedShows(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    show_name = models.TextField()
    show_id = models.IntegerField()
    air_time = models.TimeField()
    air_days = models.TextField()
    summary = models.TextField()
    network = models.CharField(max_length=255)


class UnwatchedEpisode(models.Model):
    followed_show = models.ForeignKey(FollowedShows, on_delete=models.CASCADE)
    watched = models.BooleanField(default=False)
    episode_id = models.IntegerField()
    episode_name = models.TextField()
    season = models.IntegerField()
    episode_number = models.IntegerField()
    air_time = models.TimeField()
    air_date = models.DateField()
    air_stamp = models.DateTimeField()
    summary = models.TextField()

    class Meta:
        ordering = ["season", "episode_number"]
        unique_together = (('followed_show', 'episode_id'),)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. A valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

users/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from .models import FollowedShows
from .forms import SignUpForm
from .tokens import account_activation_token

# Create your views here.

days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']


def prev_day(day):
    return days[days.index(day)-1]


def next_day(day):
    return days[days.index(day)+1] if days.index(day) < len(days) - 1 else days[0]


@login_required
def followed_shows(request, air_day=None):
    """View to display shows followed by user"""
    day = air_day or datetime.datetime.now().strftime('%A')
    day = day.lower()
    shows = FollowedShows.objects.filter(user=request.user, air_days__contains=day)
    return render(
        request,
        'users/followed.html',
        {
            'shows': shows,
            'current_day': day,
            'prev_day': prev_day(day),
            'next_day': next_day(day)
         }
    )


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your FollowIt Account'
            message = render_to_string('users/account_activation_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('users:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'users/register.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'users/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('schedule:schedules')
    else:
        return render(request, 'users/account_activation_invalid.html')


def home_page(request):
    return render(request, 'home/index.html')

users/templates/users/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/account_activation_invalid.html
{% extends 'base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

users/templates/users/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

users/templates/users/followed.html
{% extends 'base.html' %}
{% load format_time %}
{% load get_person %}

{% block content %}

  <div class="container">
  <div>
    <a href="{% url 'users:followed' %}">Today</a>
    <div class="input-group d-flex justify-content-center">
      <span class="input-group-btn">
        <a class="btn btn-info" href="{% url 'users:followed_day' prev_day %}">Previous day</a>
      </span>
      <label for="current-day" aria-hidden="true" hidden>Current day</label>
      <input id="current-day" type="text" readonly value="{{ current_day }}" class="text-center form-control-plaintext" />
      <span class="input-group-btn">
        <a class="btn btn-info" href="{% url 'users:followed_day' next_day %}">Next day</a>
      </span>
    </div>
  </div>
  {% if shows %}
    <!-- div tags used instead of ul/li because adding row to the <ul> doesn't work maybe I'm doing it wrong -->
    <div class="list-group">
      <div class="row">
        {% for show in shows %}
          <div class="list-group-item d-flex flex-wrap justify-content-between col-lg-6 col-12">
            <div class="align-self-center order-2"><a href="{% url 'shows:show' show.show_id %}">{{ show.show_name }}</a></div>
            <div class="align-self-center order-3">
              <i class="fa fa-clock-o" aria-hidden="true"></i>
              <time datetime="{{ show.air_time }}">{{ show.air_time|time }}</time>
            </div>
            <div class="align-self-center order-1">
              {% if show.status|lower != 'ended' %}
                {% if user|is_following:show.show_id %}
                  <button id="show-{{ show.show_id }}" class="order-1 follow-btn btn btn-success">Following</button>
                {% else %}
                  <button id="show-{{ show.show_id }}" class="order-1 follow-btn btn btn-primary">Follow</button>
                {% endif %}
              {% else %}
                <span class="text-center">Status: {{ show.status }}</span>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% else %}
  <div>No shows today!</div>
  {% endif %}
  </div>
{% endblock %}

{% block scripts %}
<script>
var token = "{{ csrf_token }}";
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", token);
        }
    }
});

  $('.follow-btn').click(function() {
    var self = $(this);
    var show = this.id.split('-')[1];
    $.post(
      '/shows/follow/', { show: show }
      )
      .done(function(results) {
        console.log(results);
        if (results.following) {
          self.addClass('btn-success').removeClass('btn-primary');
          self.text('following')
        } else {
          self.addClass('btn-primary').removeClass('btn-success');
          self.text('Follow');
        }
      })
      .fail(function(results) {console.log(results)})
  });
</script>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h2>Sign up</h2>
    <form method="post" novalidate>
      {% csrf_token %}
      {% include 'includes/bs4_form.html' with form=form %}
      <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
  </div>

{% endblock %}