FollowIt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('users.urls')),
    url(r'^shows/', include('shows.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

schedule/urls.py
from django.conf.urls import url

from . import views

app_name = 'schedule'
urlpatterns = [
    url(r'^$', views.SchedulesView.as_view(), name='schedules'),
    url(r'^(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$', views.SchedulesView.as_view(), name='schedules_by_date')
]

shows/urls.py
from django.conf.urls import url

from . import views

app_name = 'shows'
urlpatterns = [
    url(r'^(?P<show_id>[0-9]+)$', views.ShowView.as_view(), name="show"),
    url(r'^follow/', views.follow_shows, name='follow_show')
]

schedule/models.py
from django.db import models

# Create your models here.

schedule/views.py
from django.shortcuts import render, HttpResponse, Http404
from django.views.generic import TemplateView
from datetime import datetime, timedelta
from pytv import Schedule
from pytv.tvmaze_utility import ApiError

# Create your views here.


# def index(request):
#     return render(request, 'schedule/base.html')


def offset_date(date, offset):
    return (date + timedelta(days=offset)).strftime('%Y-%m-%d')


class SchedulesView(TemplateView):
    template_name = 'schedule/schedules.html'

    def get_context_data(self, date=None, **kwargs):
        if date:
            try:
                current_day = datetime.strptime(date, '%Y-%m-%d')
            except ValueError:
                raise Http404
        else:
            current_day = datetime.now()
        today = datetime.now()
        context = super().get_context_data(**kwargs)
        context['schedule'] = Schedule(date=current_day.strftime('%Y-%m-%d'))
        context['today'] = today.strftime('%Y-%m-%d')
        context['current_day'] = current_day.strftime('%a, %Y-%m-%d')
        context['prev_day'] = offset_date(current_day, -1)
        context['next_day'] = offset_date(current_day, 1)
        context['prev_week'] = offset_date(current_day, -7)
        context['next_week'] = offset_date(current_day, 7)
        return context

schedule/templates/schedule/base.html
{% extends 'base.html' %}

{% block content %}
<div>hi</div>
{% endblock %}

schedule/templates/schedule/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

schedule/templates/schedule/schedules.html
{% extends 'schedule/base.html' %}
{% load staticfiles %}
{% load format_time %}
{% load get_person %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'schedule/styles.css' %}">
{% endblock %}


{% block content %}
  <div class="container">
    <Label for="sched-filter" hidden aria-hidden="True">Filter by name</Label>
    <input id="sched-filter" class="form-control" placeholder="Filter by name" />
    <a href="{% url 'schedule:schedules' %}">Today</a>
    <div class="input-group">
      <span class="input-group-btn d-none d-sm-inline">
        <a class="btn btn-info" href="{% url 'schedule:schedules_by_date' prev_week %}" type="button">
          <i class="fa fa-fast-backward" aria-hidden="true"></i>
        </a>
      </span>
      <span class="input-group-btn">
        <a href="{% url 'schedule:schedules_by_date' prev_day %}" class="btn btn-info" type="button">
          <i class="fa fa-arrow-left" aria-hidden="true"></i>
        </a>
      </span>
      <input type="text" class="form-control-plaintext" readonly value="{{ current_day }}" aria-label="Product name">
      <span class="input-group-btn">
        <a href="{% url 'schedule:schedules_by_date' next_day %}" class="btn btn-info" type="button">
          <i class="fa fa-arrow-right" aria-hidden="true"></i>
        </a>
      </span>
      <span class="input-group-btn d-none d-sm-inline">
        <a href="{% url 'schedule:schedules_by_date' next_week %}" class="btn btn-info" type="button">
          <i class="fa fa-fast-forward" aria-hidden="true"></i>
        </a>
      </span>
    </div>
    <div class="card-columns">
      {% for episode in schedule.episodes %}

        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <h4 class="card-title">{{ episode.show.name }}</h4>
              <time datetime="{{ episode.airtime }}">
                {{ episode.airtime|time_12 }}
              </time>
            </div>
            <div class="d-flex flex-wrap justify-content-between">
              <h6 class="card-subtitle mb-2 text-muted">Episode: {{ episode.name }}</h6>
              <h6 class="card-subtitle mb-2 text-muted">Type: {{ episode.show.type }}</h6>
              <h6 class="card-subtitle mb-2 text-muted">Network: {{ episode.show.network.name }}</h6>
            </div>
            <div class="card-text episode-summary">
              {% if episode.summary %}
                {{ episode.summary|safe }}
              {% else %}
                <p>No summary entered.</p>
              {% endif %}
            </div>
            <div class="d-flex justify-content-between">
              {% if user.is_authenticated %}
                {% if user|is_following:episode.show.id %}
                  <button id="show-{{ episode.show.id }}" class="follow-btn btn btn-success">Following</button>
                {% else %}
                  <button id="show-{{ episode.show.id }}" class="follow-btn btn btn-primary">Follow</button>
                {% endif %}
              {% else %}
                <a href="{% url 'login' %}?next=/schedule/" class="btn btn-primary" role="button" aria-pressed="true">Follow</a>
              {% endif %}
              <a href="{% url 'shows:show' episode.show.id %}" class="btn btn-info">View show</a>
            </div>
          </div>
        </div>

      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.js"></script>
<script>
var token = "{{ csrf_token }}";
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", token);
        }
    }
});

  $('.follow-btn').click(function() {
    var self = $(this);
    var show = this.id.split('-')[1];
    $.post(
      '/shows/follow/', { show: show }
      )
      .done(function(results) {
        if (results.following) {
          self.addClass('btn-success').removeClass('btn-primary');
          self.text('Following')
        } else {
          self.addClass('btn-primary').removeClass('btn-success');
          self.text('Follow');
        }
      })
      .fail(function(results) {console.log(results)})
  });
  const filterInput = $('#sched-filter');
  const cards = $('.card');
  const filterCards = function(e) {
    cards.each((i, obj) => {
      const element = $(obj);
      if (element.find('.card-title').text().toLowerCase().includes(e.target.value.toLowerCase())) {
        element.css('display', 'inline-block')
      } else {
        element.css('display', 'none');
      }
    });
  };


filterInput.keyup(_.debounce(filterCards, 400));
</script>
{% endblock %}